### ISSUE TITLE
The latest version cannot run on linux

### ISSUE THREAD

**Issue by yt4766269** [Dentosal/python-sc2#12]
I upgrade the python-sc2 package to 0.4.5 and I find I cannot run even the worker rush script on my computer whose operation system is linux. Here is the error report:

Error: expected response: 2, actual response: 0
Error reported: Must first start a game with CreateGame or specify ports to join another client's game
Traceback (most recent call last):
INFO:sc2.sc2process:Cleanup complete
  File "/home/wangjian/DeepLearning/starcraft/MacroOperation/MacroOperation.py", line 18, in <module>
    main()
  File "/home/wangjian/DeepLearning/starcraft/MacroOperation/MacroOperation.py", line 15, in main
    ], realtime=True)
  File "/home/wangjian/anaconda3/lib/python3.6/site-packages/sc2/main.py", line 127, in run_game
    _host_game(map_settings, players, **kwargs)
  File "/home/wangjian/anaconda3/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/wangjian/anaconda3/lib/python3.6/site-packages/sc2/main.py", line 88, in _host_game
    result = await _play_game(players[0], client, realtime, portconfig, step_time_limit)
  File "/home/wangjian/anaconda3/lib/python3.6/site-packages/sc2/main.py", line 65, in _play_game
    player_id = await client.join_game(player.race, portconfig=portconfig)
  File "/home/wangjian/anaconda3/lib/python3.6/site-packages/sc2/client.py", line 52, in join_game
    result = await self._execute(join_game=req)
  File "/home/wangjian/anaconda3/lib/python3.6/site-packages/sc2/protocol.py", line 56, in _execute
    raise ProtocolError(f"{response.error}")
sc2.protocol.ProtocolError: ["Must first start a game with CreateGame or specify ports to join another client's game"]

**Comment by Dentosal** [comment]
Looks weird. I'll look into this. Probably the join request should retry the connection after a while, since the game might not be created yet.

Could you specify the linux version you're running and the version of the SC2 binary.

**Comment by yt4766269** [comment]
I'm using a linux distribution based on debian, called Deepin. Its version is 15.5. Maybe I should try it on other distributions like ubuntu or centos.
My SC2 binary is 4.0.2 .

**Comment by yt4766269** [comment]
Currently I'm using the 0.3.1 version of python-sc2. It performs well on my linux system.

**Comment by yt4766269** [comment]
I tried on ubuntu 16.04 and got the same result:
![image](https://user-images.githubusercontent.com/13883222/35440030-93740542-02d8-11e8-983e-5a4be33dcc2f.png)

**Comment by Dentosal** [comment]
I think I know what the issue is. I'll fix this when I have time, hopefully quite soon.

**Comment by yt4766269** [comment]
Thanks!

**Comment by Dentosal** [comment]
I think I fixed it with the latest version. At least I cannot reproduce it anymore with newest Linux SC2 binary.

**Comment by Dentosal** [comment]
I close the issue, feel free to reopen if there is still an issue.

**Comment by yt4766269** [comment]
I upgraded to version 0.7.7, but the problem is still there.

**Comment by Dentosal** [comment]
Ok. Trying to reproduce this soon.

**Comment by yt4766269** [comment]
What is the problem there? Has is been reproduced or solved?

**Comment by Dentosal** [comment]
Reproduced. Ubuntu 17.10, Python 3.6, python-sc2 0.7.8.

**Comment by yt4766269** [comment]
Hoping the problem can be solved soon.

**Comment by Dentosal** [comment]
I managed to fix this. Probably it's just about the casing of the maps folder name; it seems to be `Maps` on macOS and `maps` on Linux. The error was not properly handled. Deploying fix soon.

**Comment by yt4766269** [comment]
As pytorch has released its windows version, it is ok for me to run python-sc2 on windows now.
